// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type AccountingCompanyChartOfAccount struct {
	ID                string       `db:"id"`
	CompanyID         string       `db:"company_id"`
	BranchID          string       `db:"branch_id"`
	AccountCode       string       `db:"account_code"`
	AccountName       string       `db:"account_name"`
	AccountGroup      string       `db:"account_group"`
	BankName          string       `db:"bank_name"`
	BankAccountNumber string       `db:"bank_account_number"`
	BankCode          string       `db:"bank_code"`
	OpeningBalance    int64        `db:"opening_balance"`
	IsDeleted         bool         `db:"is_deleted"`
	CreatedAt         sql.NullTime `db:"created_at"`
	UpdatedAt         sql.NullTime `db:"updated_at"`
}

type AccountingCompanyFiscalYear struct {
	CompanyID   string       `db:"company_id"`
	StartPeriod time.Time    `db:"start_period"`
	EndPeriod   time.Time    `db:"end_period"`
	CreatedAt   sql.NullTime `db:"created_at"`
	UpdatedAt   sql.NullTime `db:"updated_at"`
}
