// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
)

type NotificationNotification struct {
	ID        string       `db:"id"`
	CompanyID string       `db:"company_id"`
	BranchID  string       `db:"branch_id"`
	Title     string       `db:"title"`
	Content   string       `db:"content"`
	Type      string       `db:"type"`
	IsRead    bool         `db:"is_read"`
	IsDeleted bool         `db:"is_deleted"`
	CreatedAt sql.NullTime `db:"created_at"`
}
