// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	DeleteNotification(ctx context.Context, id string) error
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]GetNotificationsRow, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (NotificationNotification, error)
	ReadNotification(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
