// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type PurchasingPurchasing struct {
	ID        string       `db:"id"`
	BranchID  string       `db:"branch_id"`
	Code      string       `db:"code"`
	Name      string       `db:"name"`
	Address   string       `db:"address"`
	Type      string       `db:"type"`
	IsDeleted bool         `db:"is_deleted"`
	CreatedAt sql.NullTime `db:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at"`
}

type PurchasingPurchasingRack struct {
	ID          string       `db:"id"`
	PurchasingID string       `db:"purchasing_id"`
	Name        string       `db:"name"`
	CreatedAt   sql.NullTime `db:"created_at"`
	UpdatedAt   sql.NullTime `db:"updated_at"`
	IsDeleted   bool         `db:"is_deleted"`
}
