// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const deleteWarehouse = `-- name: DeleteWarehouse :exec
UPDATE warehouse.warehouses
SET is_deleted = true
WHERE id = $1
`

func (q *Queries) DeleteWarehouse(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWarehouse, id)
	return err
}

const deleteWarehouseRack = `-- name: DeleteWarehouseRack :exec
UPDATE warehouse.warehouse_racks
SET is_deleted = true
WHERE id = $1
`

func (q *Queries) DeleteWarehouseRack(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWarehouseRack, id)
	return err
}

const getWarehouseRacks = `-- name: GetWarehouseRacks :many
SELECT id, warehouse_id, name
FROM warehouse.warehouse_racks
WHERE CASE WHEN $4::bool THEN id = $1
ELSE warehouse_id = $2 AND name LIKE $3 AND is_deleted = false END
`

type GetWarehouseRacksParams struct {
	ID          string `db:"id"`
	WarehouseID string `db:"warehouse_id"`
	Name        string `db:"name"`
	IsFilterID  bool   `db:"is_filter_id"`
}

type GetWarehouseRacksRow struct {
	ID          string `db:"id"`
	WarehouseID string `db:"warehouse_id"`
	Name        string `db:"name"`
}

func (q *Queries) GetWarehouseRacks(ctx context.Context, arg GetWarehouseRacksParams) ([]GetWarehouseRacksRow, error) {
	rows, err := q.db.QueryContext(ctx, getWarehouseRacks,
		arg.ID,
		arg.WarehouseID,
		arg.Name,
		arg.IsFilterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWarehouseRacksRow
	for rows.Next() {
		var i GetWarehouseRacksRow
		if err := rows.Scan(&i.ID, &i.WarehouseID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarehouses = `-- name: GetWarehouses :many
SELECT id, branch_id, code, name, address, type
FROM warehouse.warehouses
WHERE CASE WHEN $4::bool THEN id = $1
ELSE CASE WHEN $5::bool THEN branch_id = ANY($6::text [])
ELSE branch_id = $2 AND name LIKE $3
AND is_deleted = false END END
`

type GetWarehousesParams struct {
	ID                  string   `db:"id"`
	BranchID            string   `db:"branch_id"`
	Name                string   `db:"name"`
	IsFilterID          bool     `db:"is_filter_id"`
	IsFilterMultiBranch bool     `db:"is_filter_multi_branch"`
	BranchIds           []string `db:"branch_ids"`
}

type GetWarehousesRow struct {
	ID       string `db:"id"`
	BranchID string `db:"branch_id"`
	Code     string `db:"code"`
	Name     string `db:"name"`
	Address  string `db:"address"`
	Type     string `db:"type"`
}

func (q *Queries) GetWarehouses(ctx context.Context, arg GetWarehousesParams) ([]GetWarehousesRow, error) {
	rows, err := q.db.QueryContext(ctx, getWarehouses,
		arg.ID,
		arg.BranchID,
		arg.Name,
		arg.IsFilterID,
		arg.IsFilterMultiBranch,
		pq.Array(arg.BranchIds),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWarehousesRow
	for rows.Next() {
		var i GetWarehousesRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Code,
			&i.Name,
			&i.Address,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWarehouse = `-- name: UpsertWarehouse :one
INSERT INTO warehouse.warehouses(id, branch_id, code, name, address, type)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id)
DO UPDATE SET
    branch_id = EXCLUDED.branch_id,
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    type = EXCLUDED.type,
    updated_at = NOW()
RETURNING id, branch_id, code, name, address, type, is_deleted, created_at, updated_at
`

type UpsertWarehouseParams struct {
	ID       string `db:"id"`
	BranchID string `db:"branch_id"`
	Code     string `db:"code"`
	Name     string `db:"name"`
	Address  string `db:"address"`
	Type     string `db:"type"`
}

func (q *Queries) UpsertWarehouse(ctx context.Context, arg UpsertWarehouseParams) (WarehouseWarehouse, error) {
	row := q.db.QueryRowContext(ctx, upsertWarehouse,
		arg.ID,
		arg.BranchID,
		arg.Code,
		arg.Name,
		arg.Address,
		arg.Type,
	)
	var i WarehouseWarehouse
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.Type,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWarehouseRack = `-- name: UpsertWarehouseRack :one
INSERT INTO warehouse.warehouse_racks(id, warehouse_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (id)
DO UPDATE SET
    warehouse_id = EXCLUDED.warehouse_id,
    name = EXCLUDED.name,
    updated_at = NOW()
RETURNING id, warehouse_id, name, created_at, updated_at, is_deleted
`

type UpsertWarehouseRackParams struct {
	ID          string `db:"id"`
	WarehouseID string `db:"warehouse_id"`
	Name        string `db:"name"`
}

func (q *Queries) UpsertWarehouseRack(ctx context.Context, arg UpsertWarehouseRackParams) (WarehouseWarehouseRack, error) {
	row := q.db.QueryRowContext(ctx, upsertWarehouseRack, arg.ID, arg.WarehouseID, arg.Name)
	var i WarehouseWarehouseRack
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
