// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	GetWarehouses(ctx context.Context, arg GetWarehousesParams) ([]GetWarehousesRow, error)
	UpsertWarehouse(ctx context.Context, arg UpsertWarehouseParams) (WarehouseWarehouse, error)
}

var _ Querier = (*Queries)(nil)
