// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
)

type AccountUser struct {
	ID          string         `db:"id"`
	ImageUrl    string         `db:"image_url"`
	Fullname    string         `db:"fullname"`
	Nickname    string         `db:"nickname"`
	Email       sql.NullString `db:"email"`
	PhoneNumber string         `db:"phone_number"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
}

type AccountUserAddress struct {
	UserID      string       `db:"user_id"`
	Country     string       `db:"country"`
	Province    string       `db:"province"`
	Regency     string       `db:"regency"`
	District    string       `db:"district"`
	FullAddress string       `db:"full_address"`
	CreatedAt   sql.NullTime `db:"created_at"`
	UpdatedAt   sql.NullTime `db:"updated_at"`
}

type AccountUserInfo struct {
	UserID    string       `db:"user_id"`
	Key       string       `db:"key"`
	Value     string       `db:"value"`
	CreatedAt sql.NullTime `db:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at"`
}

type AccountUserPassword struct {
	UserID    string       `db:"user_id"`
	Password  string       `db:"password"`
	CreatedAt sql.NullTime `db:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at"`
}
