// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUser(ctx context.Context, id string) (AccountUser, error)
	GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (string, error)
	GetUserPassword(ctx context.Context, userID string) (AccountUserPassword, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertUserAddresses(ctx context.Context, arg UpsertUserAddressesParams) error
	UpsertUserInfo(ctx context.Context, arg UpsertUserInfoParams) error
	UpsertUserPassword(ctx context.Context, arg UpsertUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
