// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO account.users (id, fullname, nickname, email, phone_number)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID          string         `db:"id"`
	Fullname    string         `db:"fullname"`
	Nickname    string         `db:"nickname"`
	Email       sql.NullString `db:"email"`
	PhoneNumber string         `db:"phone_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Fullname,
		arg.Nickname,
		arg.Email,
		arg.PhoneNumber,
	)
	return err
}

const upsertUserInfo = `-- name: UpsertUserInfo :exec
INSERT INTO account.user_infos(user_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key)
DO UPDATE SET value = EXCLUDED.value
`

type UpsertUserInfoParams struct {
	UserID string `db:"user_id"`
	Key    string `db:"key"`
	Value  string `db:"value"`
}

func (q *Queries) UpsertUserInfo(ctx context.Context, arg UpsertUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserInfo, arg.UserID, arg.Key, arg.Value)
	return err
}

const upsertUserPassword = `-- name: UpsertUserPassword :exec
INSERT INTO account.user_passwords(user_id, password)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET password = EXCLUDED.password
`

type UpsertUserPasswordParams struct {
	UserID   string `db:"user_id"`
	Password string `db:"password"`
}

func (q *Queries) UpsertUserPassword(ctx context.Context, arg UpsertUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPassword, arg.UserID, arg.Password)
	return err
}
