// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	GetBrands(ctx context.Context, arg GetBrandsParams) ([]GetBrandsRow, error)
	GetGroups(ctx context.Context, arg GetGroupsParams) ([]GetGroupsRow, error)
	GetUnits(ctx context.Context, arg GetUnitsParams) ([]GetUnitsRow, error)
	InsertBrand(ctx context.Context, arg InsertBrandParams) (InventoryBrand, error)
	InsertGroup(ctx context.Context, arg InsertGroupParams) (InventoryGroup, error)
	InsertUnit(ctx context.Context, arg InsertUnitParams) (InventoryUnit, error)
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (InventoryBrand, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (InventoryGroup, error)
	UpdateUnit(ctx context.Context, arg UpdateUnitParams) (InventoryUnit, error)
}

var _ Querier = (*Queries)(nil)
